# Generated by Django 3.2.8 on 2021-11-22 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20211122_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='movie',
        ),
        migrations.AddField(
            model_name='comment',
            name='review',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='movies.review'),
            preserve_default=False,
        ),
    ]
